# This package contains the subset of SPI.h that is used by Tiny Alpaca Server,
# and the libraries TAS uses, for the sake of building on host, but without any
# expectation it does anything.

cc_library(
    name = "spi",
    srcs = ["spi.cc"],
    hdrs = ["spi.h"],
)
