# TODO(jamessynge): describe this package.

cc_library(
    name = "array",
    hdrs = ["array.h"],
    deps = [
        "//mcucore/src:mcucore_platform",
        "//mcucore/src/log",
    ],
)

cc_library(
    name = "array_view",
    hdrs = ["array_view.h"],
    deps = [
        "//mcucore/src:mcucore_platform",
        "//mcucore/src/log",
    ],
)

cc_library(
    name = "flash_string_table",
    srcs = ["flash_string_table.cc"],
    hdrs = ["flash_string_table.h"],
    deps = [
        "//mcucore/src:mcucore_platform",
        "//mcucore/src/log",
    ],
)
