# TODO(jamessynge): describe this package.

cc_library(
    name = "watchdog",
    srcs = ["watchdog.cc"],
    hdrs = ["watchdog.h"],
    deps = [
        "//mcucore/extras/host/arduino:avr_wdt",
        "//mcucore/src:logging",
        "//mcucore/src:mcucore_platform",
    ],
)
