# TODO(jamessynge): describe this package.

cc_test(
    name = "timer_counter_test",
    srcs = ["timer_counter_test.cc"],
    deps = [
        "//absl/log",
        "//absl/time",
        "//googletest:gunit_main",
        "//mcucore/extras/host/arduino",
        "//mcucore/extras/test_tools:print_value_to_std_string",
        "//mcucore/src/platform/avr:timer_counter",
    ],
)
