# TODO(jamessynge): describe this package.

cc_test(
    name = "array_test",
    srcs = ["array_test.cc"],
    deps = [
        "//googletest:gunit_main",
        "//mcucore/src/container:array",
    ],
)

cc_test(
    name = "array_view_test",
    srcs = ["array_view_test.cc"],
    deps = [
        "//googletest:gunit_main",
        "//mcucore/src/container:array_view",
    ],
)

cc_test(
    name = "flash_string_table_test",
    srcs = ["flash_string_table_test.cc"],
    deps = [
        "//googletest:gunit_main",
        "//mcucore/src/container:flash_string_table",
        "//mcucore/src/strings:progmem_string_data",
    ],
)
