cc_binary(
    name = "test_literal_in_progmem",
    srcs = ["test_literal_in_progmem.ino.cc"],
    tags = [
        # "local",
        # "manual",
    ],
    deps = [
        "//mcucore/extras/host/arduino",
        "//mcucore/extras/host/arduino:arduino_main",
        "//mcucore/src:McuCore",
    ],
)
