#ifndef MCUCORE_EXTRAS_TEST_TOOLS_EEPROM_EXAMPLE_DOMAINS_H_
#define MCUCORE_EXTRAS_TEST_TOOLS_EEPROM_EXAMPLE_DOMAINS_H_

// Example domains for testing.

#include "eeprom/eeprom_tag.h"

MCU_DECLARE_DOMAIN(1);
MCU_DECLARE_NAMED_DOMAIN(DomainTwo, 2);

#endif  // MCUCORE_EXTRAS_TEST_TOOLS_EEPROM_EXAMPLE_DOMAINS_H_
