# Implementations of some C++ Standard Library features for the
# Arduino / avr-libc environment, which doesn't include those libraries;
# avr-libc primarily has a C libraries.

cc_library(
    name = "utility",
    hdrs = ["utility.h"],
    deps = [
        "//mcucore/src:mcucore_platform",
        "//mcucore/src:type_traits",
    ],
)
