# TODO(jamessynge): describe this package.

cc_library(
    name = "check_sink_test_base",
    hdrs = ["check_sink_test_base.h"],
    deps = [
        "//absl/strings",
        "//googletest:gunit_headers",
        "//mcucore/extras/test_tools:print_to_std_string",
        "//mcucore/src/log:log_sink",
    ],
)
