#ifndef MCUCORE_EXTRAS_HOST_ETHERNET5500_ETHERNET_CONFIG_H_
#define MCUCORE_EXTRAS_HOST_ETHERNET5500_ETHERNET_CONFIG_H_

#include <inttypes.h>

#define MAX_SOCK_NUM 8

#endif  // MCUCORE_EXTRAS_HOST_ETHERNET5500_ETHERNET_CONFIG_H_
