# Two source files, each defining separate EEPROM domains.

cc_library(
    name = "example1",
    srcs = ["example1.cc"],
    hdrs = ["example1.h"],
    deps = ["//mcucore/src:McuCore"],
)

cc_library(
    name = "example2",
    srcs = ["example2.cc"],
    hdrs = ["example2.h"],
    deps = ["//mcucore/src:McuCore"],
)
