#ifndef MCUCORE_EXAMPLES_EEPROM_TLV_SRC_EXAMPLE2_H_
#define MCUCORE_EXAMPLES_EEPROM_TLV_SRC_EXAMPLE2_H_

#include <McuCore.h>

MCU_DECLARE_NAMED_DOMAIN(ExampleDomain2, 18);

void Example2Func();

#endif  // MCUCORE_EXAMPLES_EEPROM_TLV_SRC_EXAMPLE2_H_
