#ifndef MCUCORE_EXAMPLES_EEPROM_TLV_SRC_EXAMPLE1_H_
#define MCUCORE_EXAMPLES_EEPROM_TLV_SRC_EXAMPLE1_H_

#include <McuCore.h>

MCU_DECLARE_DOMAIN(17);

void Example1Func();

#endif  // MCUCORE_EXAMPLES_EEPROM_TLV_SRC_EXAMPLE1_H_
