# Tests of the mcucore host implementation of the EEPROM Arduino library.

cc_test(
    name = "eeprom_test",
    srcs = ["eeprom_test.cc"],
    deps = [
        "//googletest:gunit_main",
        "//mcucore/extras/host/eeprom",
        "//mcucore/extras/test_tools:eeprom_test_utils",
    ],
)
